/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MessagesIndexRouteImport } from './routes/messages/index'
import { Route as LogsIndexRouteImport } from './routes/logs/index'
import { Route as LogsNewRouteImport } from './routes/logs/new'
import { Route as LogsIdRouteImport } from './routes/logs/$id'
import { Route as CategoryIdRouteImport } from './routes/category/$id'
import { Route as AuthSetupRouteImport } from './routes/auth/setup'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthPasswordResetRouteImport } from './routes/auth/password-reset'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as LogsIdIndexRouteImport } from './routes/logs/$id/index'
import { Route as LogsIdEditRouteImport } from './routes/logs/$id/edit'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsIndexRoute = LogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsNewRoute = LogsNewRouteImport.update({
  id: '/logs/new',
  path: '/logs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsIdRoute = LogsIdRouteImport.update({
  id: '/logs/$id',
  path: '/logs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryIdRoute = CategoryIdRouteImport.update({
  id: '/category/$id',
  path: '/category/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSetupRoute = AuthSetupRouteImport.update({
  id: '/auth/setup',
  path: '/auth/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPasswordResetRoute = AuthPasswordResetRouteImport.update({
  id: '/auth/password-reset',
  path: '/auth/password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsIdIndexRoute = LogsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LogsIdRoute,
} as any)
const LogsIdEditRoute = LogsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => LogsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/password-reset': typeof AuthPasswordResetRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/setup': typeof AuthSetupRoute
  '/category/$id': typeof CategoryIdRoute
  '/logs/$id': typeof LogsIdRouteWithChildren
  '/logs/new': typeof LogsNewRoute
  '/logs/': typeof LogsIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/logs/$id/edit': typeof LogsIdEditRoute
  '/logs/$id/': typeof LogsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/password-reset': typeof AuthPasswordResetRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/setup': typeof AuthSetupRoute
  '/category/$id': typeof CategoryIdRoute
  '/logs/new': typeof LogsNewRoute
  '/logs': typeof LogsIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/logs/$id/edit': typeof LogsIdEditRoute
  '/logs/$id': typeof LogsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/password-reset': typeof AuthPasswordResetRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/setup': typeof AuthSetupRoute
  '/category/$id': typeof CategoryIdRoute
  '/logs/$id': typeof LogsIdRouteWithChildren
  '/logs/new': typeof LogsNewRoute
  '/logs/': typeof LogsIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/logs/$id/edit': typeof LogsIdEditRoute
  '/logs/$id/': typeof LogsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/auth/login'
    | '/auth/password-reset'
    | '/auth/register'
    | '/auth/setup'
    | '/category/$id'
    | '/logs/$id'
    | '/logs/new'
    | '/logs/'
    | '/messages/'
    | '/logs/$id/edit'
    | '/logs/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/auth/login'
    | '/auth/password-reset'
    | '/auth/register'
    | '/auth/setup'
    | '/category/$id'
    | '/logs/new'
    | '/logs'
    | '/messages'
    | '/logs/$id/edit'
    | '/logs/$id'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/auth/login'
    | '/auth/password-reset'
    | '/auth/register'
    | '/auth/setup'
    | '/category/$id'
    | '/logs/$id'
    | '/logs/new'
    | '/logs/'
    | '/messages/'
    | '/logs/$id/edit'
    | '/logs/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRoute: typeof OnboardingRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthPasswordResetRoute: typeof AuthPasswordResetRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthSetupRoute: typeof AuthSetupRoute
  CategoryIdRoute: typeof CategoryIdRoute
  LogsIdRoute: typeof LogsIdRouteWithChildren
  LogsNewRoute: typeof LogsNewRoute
  LogsIndexRoute: typeof LogsIndexRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/': {
      id: '/logs/'
      path: '/logs'
      fullPath: '/logs/'
      preLoaderRoute: typeof LogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/new': {
      id: '/logs/new'
      path: '/logs/new'
      fullPath: '/logs/new'
      preLoaderRoute: typeof LogsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/$id': {
      id: '/logs/$id'
      path: '/logs/$id'
      fullPath: '/logs/$id'
      preLoaderRoute: typeof LogsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$id': {
      id: '/category/$id'
      path: '/category/$id'
      fullPath: '/category/$id'
      preLoaderRoute: typeof CategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/setup': {
      id: '/auth/setup'
      path: '/auth/setup'
      fullPath: '/auth/setup'
      preLoaderRoute: typeof AuthSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/password-reset': {
      id: '/auth/password-reset'
      path: '/auth/password-reset'
      fullPath: '/auth/password-reset'
      preLoaderRoute: typeof AuthPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/$id/': {
      id: '/logs/$id/'
      path: '/'
      fullPath: '/logs/$id/'
      preLoaderRoute: typeof LogsIdIndexRouteImport
      parentRoute: typeof LogsIdRoute
    }
    '/logs/$id/edit': {
      id: '/logs/$id/edit'
      path: '/edit'
      fullPath: '/logs/$id/edit'
      preLoaderRoute: typeof LogsIdEditRouteImport
      parentRoute: typeof LogsIdRoute
    }
  }
}

interface LogsIdRouteChildren {
  LogsIdEditRoute: typeof LogsIdEditRoute
  LogsIdIndexRoute: typeof LogsIdIndexRoute
}

const LogsIdRouteChildren: LogsIdRouteChildren = {
  LogsIdEditRoute: LogsIdEditRoute,
  LogsIdIndexRoute: LogsIdIndexRoute,
}

const LogsIdRouteWithChildren =
  LogsIdRoute._addFileChildren(LogsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRoute: OnboardingRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthPasswordResetRoute: AuthPasswordResetRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthSetupRoute: AuthSetupRoute,
  CategoryIdRoute: CategoryIdRoute,
  LogsIdRoute: LogsIdRouteWithChildren,
  LogsNewRoute: LogsNewRoute,
  LogsIndexRoute: LogsIndexRoute,
  MessagesIndexRoute: MessagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
